### ISSUE TITLE
What your thoughts on typechecking?

### ISSUE THREAD

**Issue by stereobooster** [mdx-js/specification#16]
Hi, maintainers. Thank you for this wonderful project. 

It is very accessible, it is so easy to create  documentation or style guides (styleguidist) or component showcase (docz). The main issue of those tools is that they are fragile, you can change something in component and you will not notice how you broke your style guide. On the other side there are type systems, like TS and Flow, which can easily spot those errors.

Do you have any ideas or initiative to support some type systems? In the end MDX transpiled to JSX, so it should be possible to check at transpiled output, I guess.

**Comment by johno** [comment]
We love the idea of typechecking and would happily accept PRs to help guide users into using these tools and/or adding types to Definitely Typed.
