### ISSUE TITLE
Support for immediately invoked function expressions?

### ISSUE THREAD

**Issue by transitive-bullshit** [mdx-js/specification#20]
I'm wondering what you guys think of supporting immediately invoked function expressions within MDX ala `(() => <jsx />)()`?

I'm currently circumventing this support by importing the function content from a separate `js` file which mimics the scoping and ability to include full JS statements as opposed to just JSX expressions.

`current.mdx`
```
import example from './example'

## markdown

<example />
```

`example.js`
```js
const foo = 42

export default () => <div>{foo}</div>
```

---

`alternate.mdx`
```
## markdown

(() => {
  const foo = 42
  return <div>{foo}</div>
})()
```

For context, my motivation for supporting this within MDX relates to automating conversion of existing JS storybook stories to MDX.

cc @mergebandit @natergj

**Comment by johno** [comment]
I don't think this is something that we will support at this time. For now JS will be restricted to import/export/JSX. Though, something to note is that there's an interesting "hack" that allows you to declare variables in an MDX file by declaring them as exports:

```jsx
export const foo = 42

## markdown

<div>{foo}</div>
```

This can go as far as creating local components.

```jsx
export const MyComp = props => <h1 style={{ color: 'tomato' }} {...props} />

## markdown

<MyComp />
```

Thanks for opening up the issue!

**Comment by transitive-bullshit** [comment]
Thanks @johno 😄
