### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by jamesknelson** [mdx-js/specification#6]
It would be nice to define how props are passed to components.

MDXC supports `params paramName` at the top of the file, along with imports/exports. I think ideally, it'd look more like `props { destructured, props, ...etc }`.

**Comment by ticky** [comment]
[Markdown Component Loader](https://github.com/ticky/markdown-component-loader) also handles this by giving Markdown components access to the entire `props` object.

**Comment by johno** [comment]
Going to go ahead and close this since props are exposed to the global scope and can be accessed in JSX blocks. Thanks for opening!
