### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by jamesknelson** [mdx-js/specification#7]
One difference between MDXC and this project is that MDXC calls a single factory for code blocks, while this seems to call create both `pre` and `code` elements.

The problem with creating both `pre` and `code` is that it makes it difficult to provide different behavior between code blocks and inline backticks - code blocks have a `pre` wrapping a `code`, which means that if you configure `pre` to be something like a live code editor, it'll still receive a `code` child, when it would make more sense to just receive the raw text.

In MDXC, I handle this by using the non-HTML `codeBlock` component, and providing a default value as part of the generated code. Could that work here too?

**Comment by johno** [comment]
This isn't something that is currently documented as well as it should be. `remark` exposes an `inlineCode` node type which we persist through the MDXHAST.

This results in three different node types that components map to:

1. `inlineCode`: contained within another node type like paragraph or heading
1. `pre`: which is the wrapping element of a code block
1. `code`: which is the code element inside the `pre` of a code block.

So, the following MDX:

```jsx
# Hello, world `awesome`

<Other components={components} />

```jsx
<Other />
```

When imported and rendered:

```jsx
import React from 'react'
import Document from '../md/markdown.md'

const Pre = props => <pre style={{ color: 'red' }} {...props} />
const Code = props => <code style={{ fontWeight: 600 }} {...props} />
const InlineCode = props => <code style={{ color: 'purple' }} {...props} />

export default () => <Document components={{ pre: Pre, code: Code, inlineCode: InlineCode }} />
```

Will result in `awesome` being purple, `<Other />` being red and bold.

**Comment by jamesknelson** [comment]
Ok, makes sense. Thanks!
